# Generated by Django 4.1.1 on 2022-09-12 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealers', '0001_initial'),
        ('cars', '0001_initial'),
        ('showrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontoshowroom',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showrooms.showroomprofile'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='cars',
            field=models.ManyToManyField(through='dealers.DealerCar', to='cars.car'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealercar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AddField(
            model_name='dealercar',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='dealercar',
            unique_together={('car', 'dealer')},
        ),
    ]
