# Generated by Django 4.1.1 on 2022-09-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('dealers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercar',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealers.dealerprofile'),
        ),
    ]
