# Generated by Django 4.0 on 2022-09-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('customers', '0003_rename_cars_customerprofile_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='car',
            field=models.ManyToManyField(through='customers.CustomerCar', to='cars.Car'),
        ),
    ]
