# Generated by Django 4.0 on 2022-09-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showrooms', '0003_alter_showroomprofile_car'),
        ('customers', '0004_alter_customerprofile_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercar',
            name='showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showrooms.showroomprofile'),
        ),
    ]
